# Generated by Django 5.0.6 on 2024-05-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
